export const SCREENS = {
  DASHBOARD: 'DASHBOARD',
  HOME: 'HOMESCREEN',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  BUDGET: 'BUDGET',
  ACCOUNTS: 'ACCOUNTS',
  CHARTS: 'CHARTS',
  NEW_TRANSACTION: 'NEW_TRANSACTION',
};
