export const SCREENS = {
  DASHBOARD: 'DASHBOARD',
  HOME: 'HOMESCREEN',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  SPLASH: 'SPLASH',
  BUDGET: 'BUDGET',
  ACCOUNTS: 'ACCOUNTS',
  CHARTS: 'CHARTS',
  NEW_TRANSACTION: 'NEW_TRANSACTION',
  HOME_DRAWER:"HOME_DRAWER"
};
